---
#ipoc自动部署配置,nmon,传输脚本，crontab
#wudi 20161223
- hosts: NOVPLNMD10,NOVPLNMD11
  gather_facts: True
  vars:
      srcbasedir: /home/wudi/ipoc
      desthomedir: /home/appmon/ipoc
      killnmon: True  #是否kill已有的nmon进程
      startnmon: True  #是否立即启动nmon捕获数据到当天24点
  remote_user: appmon
  tasks:
      - name : create_dir
        file : path={{item}} state=directory mode=0755
        with_items:
                - ipoc
                - "{{ desthomedir }}/bin"
                - "{{ desthomedir }}/filebeat"

      - name : put-filebeat
        copy : src={{ srcbasedir }}/filebeat/filebeat dest={{ desthomedir }}/filebeat/filebeat mode="u=rwx" 

      - name : put-filebeat-config
        template : src={{ srcbasedir }}/template/wechat-access.yml dest={{ desthomedir }}/filebeat/wechat-access.yml mode="u=rw" 

      - name : put-startfilebeat-scrip
        copy : src={{ srcbasedir }}/script/start-filebeat.sh dest={{ desthomedir }}/bin/start-filebeat.sh mode="u=rwx" 

      - name : kill-alreday-filebeat
        raw : "ps -ef | grep /home/appmon/filebeat | grep -v grep | awk '{print $2}' | xargs kill" 
        ignore_errors: yes 

  #      - name : start-filebeat
  #        shell : "{{ desthomedir }}/bin/start-filebeat.sh"

