---
#ipoc自动部署配置,nmon,传输脚本，crontab
#wudi 20161223
- hosts: 84.239.49.81
  #gather_facts: False
  vars:
      srcbasedir: /home/wudi/ipoc
      desthomedir: /home/appmon/ipoc
      killnmon: True  #是否kill已有的nmon进程
      startnmon: True  #是否立即启动nmon捕获数据到当天24点
  remote_user: appmon
  tasks:
      - name : create dir
        file : path={{item}} state=directory mode=0755
        with_items:
                - ipoc
                - "{{ desthomedir }}/bin"
                - "{{ desthomedir }}/nmondata"

      - name : 传输nmon put nmon @CENTOS7 or @RedHat7
        copy: src={{ srcbasedir }}/nmonkit/nmon16e_x86_rhel72 dest={{ desthomedir }}/bin/nmon mode="u=rwx"
        when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and ansible_distribution_major_version == "7"
      - name : 传输nmon  put nmon @CENTOS6 or @Redhat6
        copy: src={{ srcbasedir }}/nmonkit/nmon16e_x86_rhel65 dest={{ desthomedir }}/bin/nmon mode="u=rwx"

        when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and ansible_distribution_major_version == "6"
      - name : 传输nmon  put nmon @CENTOS5 or @RedHat5
        copy: src={{ srcbasedir }}/nmonkit/nmon_x86_64_rhel54 dest={{ desthomedir }}/bin/nmon mode="u=rwx"

        when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and ansible_distribution_major_version == "5"
      - name : 传输nmon  put nmon @SLES11
        copy: src={{ srcbasedir }}/nmonkit/nmon16e_x86_sles113 dest={{ desthomedir }}/bin/nmon mode="u=rwx"

        when: ansible_distribution == 'SLES' and ansible_distribution_major_version == "11"
      - name : 传输nmon  put nmon @SLES10
        copy: src={{ srcbasedir }}/nmonkit/nmon_x86_64_sles11_oldest dest={{ desthomedir }}/bin/nmon mode="u=rwx"
        when: ansible_distribution == 'SLES' and ansible_distribution_major_version == "10"


      - name : 传输脚本 
        template: src={{ srcbasedir }}/template/{{item}} dest={{ desthomedir }}/bin/{{item}} mode="u=rwx"
        with_items:
                - snmon_nowto24.sh
                - v30-nmon2ipoc.sh

      - name : stop nmon
        # command : ps -ef | grep {{ desthomedir }}/bin/nmon | grep -v grep | awk '{print $2}' | xargs kill
        script : "{{ srcbasedir }}/script/killnmon.sh" 
        ignore_errors: yes 
        when: killnmon

      - name : 调用脚本,启动NMON采集数据call snmon_nowto24.sh
        shell : "{{ desthomedir }}/bin/snmon_nowto24.sh"
        when: startnmon

      - name : 添加nmon到crontab add crontab
        cron : "name='ipoc_nmon' minute=0 hour=0 job='{{ desthomedir }}/bin/nmon -f -t -s 60 -c 1440 -m {{ desthomedir }}/nmondata > /dev/null 2>&1' user=appmon"

      - name : 添加传输脚本到crontab add crontab v30-nmon2ipoc.sh
        cron : "name='ipoc_ftp_nmondata to logcenter' minute=5 job='{{ desthomedir }}/bin/v30-nmon2ipoc.sh' user=appmon"

      - name : sleep wait nmon make data
        command : sleep 1

      - name : sentData2ipoc
        shell : "{{ desthomedir }}/bin/v30-nmon2ipoc.sh"

      # 对数据数据库，额外增添如下处理AWR的动作 
      - name : copy_v30-awr2ipoc.sh
        copy : src={{ srcbasedir }}/script/{{item}} dest={{ desthomedir }}/bin/{{item}} mode="u=rwx"
        with_items:
               - v30-awr2ipoc.sh
               - v30-awr2ipoc-allsid.sh
        when: database is defined 

#      - name : chmod +x 
#        file : path=~/ipoc/bin/{{item}} mode="u+rwx"
#        with_items:
#               - v30-awr2ipoc.sh
#               - v30-awr2ipoc-allsid.sh
    
    
      - name : add crontab
        cron : "name='ipoc_ftp_awrdata' minute=6  job='{{desthomedir}}/bin/v30-awr2ipoc-allsid.sh'"
        when: database is defined 
    
      - name : execute v30-awr2ipoc.sh
        shell : "{{desthomedir}}/bin/v30-awr2ipoc-allsid.sh"
        when: database is defined 
