---
#ipoc自动部署配置,nmon,传输脚本，crontab
#wudi 20161223
- hosts: NOVPLNMD06 
  gather_facts: yes
  vars:
      srcbasedir: /home/wudi/ipoc
      desthomedir: /home/appmon/ipoc
      killnmon: True  #是否kill已有的nmon进程
      startnmon: True  #是否立即启动nmon捕获数据到当天24点
  remote_user: appmon
  tasks:

      - name : stop nmon
        # command : ps -ef | grep {{ desthomedir }}/bin/nmon | grep -v grep | awk '{print $2}' | xargs kill
        script : "{{ srcbasedir }}/script/killnmon.sh" 
        ignore_errors: yes 
        when: killnmon

